# Generated by Django 3.2.18 on 2023-04-20 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('membership_class', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_schedule', models.CharField(default='', max_length=50)),
                ('work_hours', models.CharField(default='', max_length=50)),
                ('title', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('profile_access', models.BooleanField()),
                ('user_access', models.BooleanField()),
                ('employee_access', models.BooleanField()),
                ('book_access', models.BooleanField()),
                ('magazine_access', models.BooleanField()),
                ('dvd_access', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
