# Generated by Django 3.2.18 on 2023-04-20 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('language_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(default='', max_length=50)),
                ('zip', models.IntegerField()),
                ('contact_number', models.CharField(max_length=20)),
                ('assistance', models.BooleanField()),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='library_database.genre')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='library_database.language')),
                ('membership_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profiles', to='library_database.membership')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('magazine_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_page', models.CharField(max_length=200)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazines', to='library_database.genre')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='magazines', to='library_database.language')),
            ],
        ),
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('dvd_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('studio', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('production_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvds', to='library_database.genre')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dvds', to='library_database.language')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.IntegerField()),
                ('edition', models.IntegerField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sample_text', models.CharField(max_length=200)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='library_database.genre')),
                ('language_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='library_database.language')),
            ],
        ),
    ]
