# Generated by Django 3.2.18 on 2023-04-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0003_alter_genre_genre_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='name',
        ),
        migrations.AlterField(
            model_name='book',
            name='sample_text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='sample_page',
            field=models.CharField(max_length=300),
        ),
    ]
