# Generated by Django 3.2.18 on 2023-04-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0004_auto_20230423_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='dvd',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='magazine',
            old_name='language_id',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='membership_id',
            new_name='membership_type',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='genre_id',
            new_name='preferred_genre',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='language_id',
            new_name='preferred_language',
        ),
    ]
