# Generated by Django 3.2.18 on 2023-04-26 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0005_auto_20230424_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=500)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='library_database.asset')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='library_database.book')),
                ('dvd_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='library_database.dvd')),
                ('magazine_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='library_database.magazine')),
            ],
        ),
    ]
