# Generated by Django 3.2.18 on 2023-04-26 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0009_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='reviews', to='library_database.profile'),
            preserve_default=False,
        ),
    ]
