# Generated by Django 3.2.18 on 2023-04-27 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0011_auto_20230426_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckedAssets',
            fields=[
                ('checked_assets_id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkedAssets', to='library_database.assettype')),
                ('book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkedAssets', to='library_database.book')),
                ('dvd_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkedAssets', to='library_database.dvd')),
                ('magazine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkedAssets', to='library_database.magazine')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkedAssets', to='library_database.profile')),
            ],
        ),
    ]
