# Generated by Django 3.2.18 on 2023-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_database', '0012_checkedassets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CheckedAssets',
            new_name='CheckedAsset',
        ),
    ]
